name: Automation Anypoint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "compile"
  specification:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Testing Strategy ( BAT CLI Integration -> bat integration-test.dwl)
        run: curl -o- 'https://s3.amazonaws.com/bat-wrapper/install.sh' | bash && echo Integration Testing Complete
        
      - name: Print Account Information
        run: >
          npm install -g anypoint-cli-v4 &&
          anypoint-cli-v4 account:user:describe --client_id e6193e8d10c24aee8f9d82c99d7f4a7c --client_secret 241615f0f39B41909D61F64d2D2a7Fd8 -o json
        
